### ISSUE TITLE
Rendering issues in the abstract Renderer class

### ISSUE THREAD

**Issue by ediamin** [rtCamp/web-stories-wp#109]
@ankitrox @divyarajmasani 

I'm trying to use the `Stories` (or as it renamed to Stories_Query) class inside the `Latest_Stories_Block::render_block()` like this,
```
	public function render_block( array $attributes ) {

		if ( false === $this->initialize_block_attributes( $attributes ) ) {
			return '';
		}

		$story_attributes = [
			'view_type'                 => ! empty( $attributes['viewType'] ) ? $attributes['viewType'] : 'circles',
			'number_of_columns'         => ! empty( $attributes['numOfColumns'] ) ? $attributes['numOfColumns'] : 2,
			'show_title'                => ! empty( $attributes['isShowingTitle'] ) ? $attributes['isShowingTitle'] : false,
			'show_author'               => ! empty( $attributes['isShowingAuthor'] ) ? $attributes['isShowingAuthor'] : false,
			'show_date'                 => ! empty( $attributes['isShowingDate'] ) ? $attributes['isShowingDate'] : false,
			'show_story_poster'         => ! empty( $attributes['isShowingStoryPlayer'] ) ? $attributes['isShowingStoryPlayer'] : true,
			'show_stories_archive_link' => ! empty( $attributes['isShowingViewAll'] ) ? $attributes['isShowingViewAll'] : false,
			'stories_archive_label'     => ! empty( $attributes['viewAllLinkLabel'] ) ? $attributes['viewAllLinkLabel'] : __( 'View all stories', 'web-stories' ),
			'list_view_image_alignment' => ! empty( $attributes['imageOnRight'] ) ? $attributes['imageOnRight'] : 'left',
		];

		$stories = new Stories( $story_attributes, $this->get_query_args() );

		return $stories->render();
	}
```

It renders fine in WP frontend, no error. But throws this fatal error in block editor
```
 Fatal error: Uncaught Error: Call to undefined function Google\Web_Stories\Stories_Renderer\amp_is_request() in /web-stories-wp/wp-content/plugins/web-stories-wp/includes/Stories_Renderer/Renderer.php on line 178
```

This happens because `\Google\Web_Stories\Plugin::load_amp_plugin_compat()` loads in `wp` action that registered in `\Google\Web_Stories\Plugin::register()` method. We can solve this by using init hook instead of wp,
```
// - add_action( 'wp', [ $this, 'load_amp_plugin_compat' ] );
add_action( 'init', [ $this, 'load_amp_plugin_compat' ] );
```

But it raises another issue. Now I get the following error,
```
PHP Notice:  Undefined property: Google\Web_Stories\Model\Story::$ID in /web-stories-wp/wp-content/plugins/web-stories-wp/includes/Stories_Renderer/Renderer.php on line 203
```
It's because `\Google\Web_Stories\Stories_Renderer\Renderer::prepare_story_modal()` called multiple times in block editor pages. So for the second time `$a_post->ID` is invalid cause $a_post is no longer `WP_Post`, after first time it's `\Google\Web_Stories\Model\Story`.

So I think we should use a condition check like `$a_post instanceof WP_Post`. 

PS -
- There is a duplicate add_action in the [init method](https://github.com/rtCamp/web-stories-wp/blob/12c7974f2c48033b040fbcbbf69c9eab0885a73d/includes/Stories_Renderer/Renderer.php#L153)
- The method name should be prepare_story_**model** instead of `prepare_story_modal`

**Comment by divyarajmasani** [comment]
Closing this one as it is not relevant anymore.
