### ISSUE TITLE
Gutenberg Block — Latest Stories 

### ISSUE THREAD

**Issue by rahul286** [rtCamp/web-stories-wp#11]
Related to https://github.com/google/web-stories-wp/issues/3064

Wireframe idea https://xd.adobe.com/view/bfc6d09d-d88b-44cb-73e9-b95f00d806e5-c9f7/?fullscreen

## Feature Checklist

**View Modes**

- [x] List View
- [x] Grid View
- [x] Circles
- [x] Carousel

**Display Options**

- [x] Show date
- [x] Show author
- [x] Show "View all stories" link
- [x] Show preview image only (otherwise uses amp-story-player)

**Sorting and Filtering**

- [x] Order by
  - [x] Newest to oldest
  - [x] Oldest to newest
  - [x] A -> Z
  - [x] Z -> A
  - [x] Random Stories
- [x] Author to filter by
- [x] Number of columns (default e.g. ~~5~~ 4)
- [x] Number of stories (default e.g 20)
- [x] Blocked: Filtering by taxonomies supported by the post type (once #489 lands)

## Phases 

- [x] Skeleton UI in Gutenberg 
- [x] Connect with Data source
- [x] Show real-time preview in Gutenberg  editor
- [x] Rendor block frontend
- [ ] ~Test with AMP (all three modes)~
- [ ] ~Write test cases~ Now tracked on https://github.com/rtCamp/web-stories-wp/issues/91

**Comment by maitreyie-chavan** [comment]
@RahiDroid The description of the issue has been updated to reflect the points discussed during the call about the default number of columns and stories. Please make the needful updates.

**Comment by maitreyie-chavan** [comment]
Colud we close this issue since our base is now ready and we are working on enhancements and bug fixing _(being tracked separately)_ ? The remaining two open points could be tracked under separate issues.

**Comment by RahiDroid** [comment]
@maitreyie-chavan I agree. Can we have an issue for test cases as well, please?

**Comment by maitreyie-chavan** [comment]
Closing this issue since majority of the points have been covered, the remaining two points will be tracked separately.
