### ISSUE TITLE
Carousel: Select a library to be used for non-AMP version of 'Carousel view type'

### ISSUE THREAD

**Issue by RahiDroid** [rtCamp/web-stories-wp#116]
## Task Description
- Since we can't use `amp-carousel` on non-AMP pages at the moment, we will be adding a carousel library for non-AMP pages.
- However, it's important to note that `amp-carousel` component is to be made available on non-AMP pages in a very near future and we will surely want to swap out whatever library we agree upon with `amp-carousel` component for non-AMP pages.

## Todo once we agree upon a carousel library
- Try and use that library in editor of Gutenberg blocks so that we can remove those _warning_ message from the editor and provide similar user experience on both editor and front-end.

**Comment by divyarajmasani** [comment]
This issue can be closed, the carousel library has been selected.

https://nickpiscitelli.github.io/Glider.js/
