### ISSUE TITLE
Latest Stories Block: Better backup mechanism for story Poster image

### ISSUE THREAD

**Issue by RahiDroid** [rtCamp/web-stories-wp#19]
## Feature Description
- Right now when we have `Show only story poster` block setting enabled for `Latest Stories Block`, it shows the poster image of the story instead of directly embedding the story. When the poster image isn't present, we use any image present in the story's first page's content. This will not work for all cases as there may be a possibility when the story will not have any images at all.

## Alternatives Considered
- Show story's title's first letter instead of the poster image. (Something similar to google account profile picture). If title is empty, we can show `WS`.
- Show a generic placeholder image.
- Show embed story if poster image isn't present. This will **not work** for all view types as some view types strictly require you to have `Show poster image only` setting enabled because embedded story doesn't work for that view type.

## Additional Context
![Screenshot 2020-11-09 at 5 29 24 PM](https://user-images.githubusercontent.com/59014930/98538659-1e6dcc00-22b1-11eb-86b7-8daf74188507.png)
Though the story editor marks these two fields `Cover Image` and `Publisher Logo` as `*Required`, we are still allowed to publish a story leaving these two fields empty. If this validation gets patched in future, we will not need to worry about backup poster image as it will always be present.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by divyarajmasani** [comment]
There is multiple layout options right, so the suggested solution may work for one but not for the other one.
For example, if we use initials as a backup then for the circular layout it will look just fine or for smaller elements, but for the carousel/expanded view it may not look good.

So, IMO following should be the order for now, and based on the feasibility we will implement.
- Use cover/poster image if available else,
- Use brand image if available else,
- Use the first image found in the story with some minimum size criteria met ( only if feasible with the timeline ), else,
- Use the Initials ( first letters ) of the author

Also, if we can make the Cover Image required to publish the story, we may not need this fallback ladder,

**Comment by RahiDroid** [comment]
> will be part of pre-publish checks. So you can assume that these (poster images) will always be there.

Closing this as mentioned validation under `Additional Context` will be patched.
