### ISSUE TITLE
Circle Carousel issue list

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#206]
## Bug  1

- The circles are not place in the center of the container. Not centre aligned, also the arrows are not clearly visible in dark background. 

## Screenshots

![image](https://user-images.githubusercontent.com/41000648/103408267-be482780-4b87-11eb-9e68-668a53216214.png)

---

**Updated screenshot of latest test cycle**

![image](https://user-images.githubusercontent.com/41000648/107216947-7b555b80-6a33-11eb-90c6-0b88a18028d1.png)

---

## ~Bug  2~

- ~View all stories link is not visible in the backend~

---

## Bug 3

- On increasing the circle size, in backend the circles are getting overlapped. In frontend the circles are shown fine but in backend those are overlapped. ( With title option enabled also the circles are overlapping in backend ) 

**Update on the issue** - Same issue exists if we increase the number of stories as well for circle view. On increasing more than 5 stories the stories gets overlapped. 

## Screenshot

https://user-images.githubusercontent.com/41000648/103734497-224c6f00-5012-11eb-9a5a-0e4b51b9ca92.mp4

 ---

**Updated image**

![image](https://user-images.githubusercontent.com/41000648/107217757-a4c2b700-6a34-11eb-8318-d8226d500e30.png)

---

## ~Bug 4~

-  ~For circle carousel - the title toggle is disabled by default. Is this intentionally? If yes, then at least we should show the title of View All stories circle. Currently, it doesn’t show in backend.~ **( View all stories link is visible so this issue becomes invalid )** 

---

## Bug 5

- If more then 5 stories are selected then in frontend 2 scrolls are shown.

## Screenshot

https://user-images.githubusercontent.com/41000648/107337001-ce84e800-6adf-11eb-81a6-e59c1656eec5.mp4

--- 

## Bug 6

- In Circle View some stories are not aligned. Number of stories are set to 11, and Order By is set to A - Z first and then Z - A with these configurations some of the stories are not aligned. This could be due to the title of the story is just 1 word and other stories title are lengthy. **This issue occurs only if Show Title is enabled** And if title is lengthy then it is affecting the circle height's.

![image](https://user-images.githubusercontent.com/41000648/107340512-df375d00-6ae3-11eb-9be7-7eb50ac20c1a.png)

---

![image](https://user-images.githubusercontent.com/41000648/107340594-f5451d80-6ae3-11eb-9149-85b73616bd08.png)

---

**Comment by pooja-muchandikar** [comment]
**8th Feb 2021 QA status on the changes done as per the client requirements**

From the description above Bug 2 and Bug 4 are not valid now hence strike off those issues. 

But Bug 1 and Bug 3 from the list still exists. 

cc: @maitreyie-chavan

**Comment by pooja-muchandikar** [comment]
@maitreyie-chavan 

Updated few more issues in the description, one issue is major as its circles are not aligned if the stories title are lengthy, its affecting the circle height. **Bug 6** from description.

**Comment by maitreyie-chavan** [comment]
Issues have been addressed
