### ISSUE TITLE
Selected Stories - Box Carousel issue list

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#221]
## Bug 1
- Stories selection pop-up: While rearranging the stories we are not showing the story title, I think we should show the title. While selecting stories story title is visible but while rearranging the story title is not visible. 

## Steps to Reproduce
- Go to selected stories > Select Box carousel
- Select some stories, observe story title is visible
- Now, click on rearrange the stories, observe the title's are not visible
- On rearranging screen the title should be visible

## Screenshots

![image](https://user-images.githubusercontent.com/41000648/103740049-8ecc6b80-501c-11eb-9e29-a783e7590704.png)

---

## Bug 2
- On click of the arrows, an box like outline is visible for the arrows. I think it shouldn't be there. ( This issue for all box/circle and grid view )

## Screenshot
![image](https://user-images.githubusercontent.com/41000648/103740455-3ea1d900-501d-11eb-86d2-771974c7a1dd.png)

---

**Comment by divyarajmasani** [comment]
The outline shown is for the accessibility purpose if we hide it, users who prefer keyboard navigation may not be able to see if the nav arrow is focused.

**Comment by pooja-muchandikar** [comment]
> Added title and author meta for the stories rearrange screen.

Checked on https://google-webstories.rt.gw/ site but the change mentioned above is not reflecting. 

![image](https://user-images.githubusercontent.com/41000648/107262831-0c91f580-6a67-11eb-91c9-4ae3a06f1393.png)

---

cc: @maitreyie-chavan

**Comment by maitreyie-chavan** [comment]
Issues have been addressed
