### ISSUE TITLE
Support for WP core themes

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#268]
**Purpose** - Provide a way to integrate web stories into the core WordPress theme's customiser settings

**Implementation notes**

- Compatible theme list - Twenty Ten onwards
- Plugin should check if the active theme is a WP core theme
- Use hooks available to extend support for web-stories
- Hook to consider - https://github.com/WordPress/wordpress-develop/blob/f2bd8d048116e40892df4d6429dad99ede2e4c12/src/wp-content/themes/twentyten/header.php#L64
- A callback on add_theme_support so that customizer UI is enabled automatically on default themes but can be disabled by user when needed

**Slack Thread** - https://rtcamp.slack.com/archives/C01E3576K1B/p1612257452018800

**Comment by divyarajmasani** [comment]
This issue has been resolved in #282, and styles were added in #305.
