### ISSUE TITLE
UX Preference - Cover or Poster image

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#27]
When an editor creates/edits Web Stories, they add a **Cover Image** for Stories. 

<img width="1033" alt="Screenshot 2020-11-09 at 9 30 53 PM" src="https://user-images.githubusercontent.com/20221326/98564874-ed9e8e80-22d2-11eb-8a3c-2a76edcaaa6c.png">

I believe AMP refers to this as **Poster Image** in code. 

https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)

**Question**

To maintain consistency at the editor's side, shall we refer this image as Cover Image in the option highlighted below? Or should we keep it as Poster?

<img width="1171" alt="Screenshot 2020-11-09 at 9 40 09 PM" src="https://user-images.githubusercontent.com/20221326/98565960-3b67c680-22d4-11eb-8f8b-3ef212fc94c7.png">

**Comment by swissspidy** [comment]
Let's use "cover" image for the story cover image consistently everywhere for now.

We can always iterate on it.

**Comment by maitreyie-chavan** [comment]
Thanks @swissspidy for confirming,

@RahiDroid please make the needful update.

**Comment by RahiDroid** [comment]
This has been updated. Will be deployed on dev sites soon.
