### ISSUE TITLE
Stories looks bigger when selected

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#283]
## Bug Description

- When for first time any block is added with stories, then the stories looks bigger and on page refresh the stories looks normal. 

## Expected Behaviour

- First time on selecting the stories should look normal.

## Steps to Reproduce

- Go to Add New Post
- Select Web Stories LIst and select any one block
- Observe the stories, the stories are looking very big and on page refresh the stories look normal. This happens first time when stories are added.

## Screenshots

https://user-images.githubusercontent.com/41000648/107329824-b78dc800-6ad6-11eb-95a6-514e415d09fb.mp4

**Comment by maitreyie-chavan** [comment]
This issue has been addressed.
