### ISSUE TITLE
Selected Stories - Unable to close the pop-up

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#284]
## Bug Description

- When selected stories block is selected an pop-up is shown to select the stories, but say if I don't want to select any story and come out of the block, I would click on close pop-up, but on doing so the pop-up is not getting closed. 

Instead the pop-up is getting reloaded.

## Expected Behaviour

- On clicking on `X` mark the pop-up should be closed even if stories are not selected. 

## Screenshots

https://user-images.githubusercontent.com/41000648/107360773-67c1f780-6afc-11eb-9ae3-d225e8d6e196.mp4

**Comment by maitreyie-chavan** [comment]
This issue has been addressed
