### ISSUE TITLE
Reader Mode related issue list

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#287]
## Reader Mode issues

- With reader mode in AMP version background is visible, without AMP it looks fine

![image](https://user-images.githubusercontent.com/41000648/107474928-4b27cd00-6b99-11eb-8d3d-019a20076c04.png)

---

- With reader mode in AMP for circle carousel the next and previous arrows are not working. If 2 carousel are present in same page.

- With reader mode in AMP version, Grid View stories appear very big.

-

**Comment by maitreyie-chavan** [comment]
These issues have been addressed
