### ISSUE TITLE
Web stories block related issues within customizer.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#301]
## Bug 1

- The title in the Story view type drop down should be `Circle Carousel` 

![image](https://user-images.githubusercontent.com/41000648/107943808-3beaba00-6fb3-11eb-9012-f4ec589cf23f.png)

---

## Bug 2

- If `Show stories` is disabled ( checkbox is unchecked ) then, Circle Size option drop-down is shown, which shouldn't be. As we are not showing stories, so stories related settings shouldn't be shown.

![image](https://user-images.githubusercontent.com/41000648/107944416-127e5e00-6fb4-11eb-8e07-1c85d498200a.png)

---

## Bug 3

- Stories archive link is not visible. On enabling `Show stories archive link` it should Archive stories link but it isn't shown.

## Bug 4

- The Circle Size should have `minimum and maximum` size limit as we have for Circle carousel block. 

Following visual is for 3 and 4th bug.

https://user-images.githubusercontent.com/41000648/107945469-adc40300-6fb5-11eb-9c46-6981efd5699a.mp4

---

**Comment by divyarajmasani** [comment]
@ankitrox please check the Bug #2 and #4

**Comment by divyarajmasani** [comment]
Issues reported here are addressed.
