### ISSUE TITLE
Core themes - Embedding stories issue list 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#302]
## Device resolution 

- Chrome
- iPad - 768x1024 and 1024x1366
- iPhone - 414x896
- iPhoneXR - 320x568
- iPhoneX - 375x812
- Moto G4 - 360x640
- Pixel 2 - 411x731
- 
- Mac - Big Sur, 1366x604
- Mac - Catalina 
- Firefox

---

## Bug 1

- The circles are not aligned in the container

![image](https://user-images.githubusercontent.com/41000648/107947461-6be88c00-6fb8-11eb-8eab-97b2466018f8.png)

---

## Bug 2

- On opening the story, the featured image of page is overlapping. Please check the following visual. 

https://user-images.githubusercontent.com/41000648/107949027-a5ba9200-6fba-11eb-95a9-b748767862e8.mp4

---

## Bug 3

- After the last story, there is lot of space. Its not looking good.

![image](https://user-images.githubusercontent.com/41000648/108021219-13f76700-7044-11eb-9b5d-1ba4cf63b6bc.png)

---

## Bug 4

- In Firebox browser below the stories, horizontal scroll is shown. In other browser's this is not available but only on firefox browser.

![image](https://user-images.githubusercontent.com/41000648/108028419-d39ee580-7051-11eb-8510-d66b24b93304.png)

---

**Comment by maitreyie-chavan** [comment]
> Bug 1, Bug 3 and Bug 4

Are addressed.

> Bug 2

@divyarajmasani this is still an issue, please could you look into it?

**Comment by maitreyie-chavan** [comment]
It was due to a sticky post
