### ISSUE TITLE
Twenty Sixteen - Core theme - embedding stories related issue list

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#303]
## Bug 1 

- With 2016 theme enabled, if `Show Title` option is enabled then the title's are not visible, as the 2016 theme background color is dark, because of which the title's are not shown.

https://user-images.githubusercontent.com/41000648/108035799-63965c80-705d-11eb-8f8b-af368cf932ea.mp4

**Comment by maitreyie-chavan** [comment]
Titles are now visible.
