### ISSUE TITLE
Twenty Fourteen - Core theme - embedding stories related issue list 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#306]
## Bug 1

- On activating 2014 theme, the embedded stories are overlapped by the theme layout.
- Story titles are not clearly visible
- There are smaller circles with scroll at the left hand side of the page

![image](https://user-images.githubusercontent.com/41000648/108497730-eaec0600-72d1-11eb-93c8-717a6821719b.png)

---

## Bug 2

- If Show stories archive link is enabled, the stories moves below and the link is also not shown. 
- Overall the embedded stories with 2014 theme doesn't look compatible. 

https://user-images.githubusercontent.com/41000648/108498558-102d4400-72d3-11eb-8b7b-426d61f88707.mp4

---

Checked in incognito mode as well and issue exists there as well. ( Similar issue on safari and firefox browser as well )

---

## Responsive

On mobile responsive devices the layout is shown above the top header which is looking fine. 
Resolution checked ( iPhone - 414x896, iPhoneXR - 320x568, iPhoneX - 375x812, Moto G4 - 360x640, Pixel 2 - 411x731 )

![image](https://user-images.githubusercontent.com/41000648/108499339-24257580-72d4-11eb-810f-e9e7f6d2c344.png)

---

- But on **iPad Pro 1024X1366** the overlapping issue is visible

![image](https://user-images.githubusercontent.com/41000648/108499531-6ea6f200-72d4-11eb-9162-ff134e738a79.png)

---

**Comment by maitreyie-chavan** [comment]
> Bug 1 has been addressed

**Comment by maitreyie-chavan** [comment]
Remaining bugs have been fixed
