### ISSUE TITLE
Twenty Fifteen - Core theme - embedding stories related issue list

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#307]
## Bug 1

- View all stories link is shown above the stories -  but as soon some users land on that page, showing view all stories link at top is not intuitive. We can show the link after the last story.

![image](https://user-images.githubusercontent.com/41000648/108502181-6486f280-72d8-11eb-9ab1-c7882dcc960e.png)

---

![image](https://user-images.githubusercontent.com/41000648/108502052-373a4480-72d8-11eb-9e9e-d46713546dac.png)

---

**Comment by divyarajmasani** [comment]
I would not mark this as a bug but an enhancement or good to have. 

cc: @maitreyie-chavan

**Comment by maitreyie-chavan** [comment]
Yup, agree with Divyaraj. Also, for now the behaviour is the same as is for Block's Circle Carousel View.

Closing this issue.
