### ISSUE TITLE
Twenty Seventeen - Core theme - embedding stories related issue list 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#308]
## Bug 1

- With 2017 theme the stories covers most of the page space
- An scroll bar is visible
- View stories link is not visible

![image](https://user-images.githubusercontent.com/41000648/108502596-09093480-72d9-11eb-9c39-92260f6afd18.png)

Same applies to responsive device as well.

**Comment by maitreyie-chavan** [comment]
Fix for this issue has been added.
