### ISSUE TITLE
Rounded Corners Option

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#38]
Add ~the option and style~ toggle button to have round corners for stories limited to the below view layouts. 

- [x] Grid view
- [x] List view
- [x] Carousel view

User should be able to choose between sharp and rounded corners.

**Comment by maitreyie-chavan** [comment]
@divyarajmasani Issue description has been updated to incorporate the request to have a toggle button for rounded corners instead of style. Please do the needful.

**Comment by divyarajmasani** [comment]
@maitreyie-chavan 
The changes required for this issue has been deployed on our dev site.

> https://rt-webstories.rt.gw/wp-admin/post.php?post=191&action=edit

**Comment by maitreyie-chavan** [comment]
@divyarajmasani The option works well and can be made available on client demo site.

One note, option title should refer to `sharp` corner instead of _square_.

**Comment by maitreyie-chavan** [comment]
This is now available in the block.
