### ISSUE TITLE
Carousel view -  Display Single Story on Mobile Viewport

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#39]
Currently, while swiping the stories in carousel layout on mobile, stories are partially shown and sharing screenspace as seen below.

![Image from iOS](https://user-images.githubusercontent.com/20221326/98995632-9a893d80-2557-11eb-9eb2-34420c5b43ed.png)

**Accepted Criteria**

Only a single story on the story should be displayed on the screen at any swiping instance.

**Comment by maitreyie-chavan** [comment]
@divyarajmasani please do share your findings for this issue, we can take the action for this issue accordingly.

**Comment by divyarajmasani** [comment]
This has been taken care of, with the carousel updates. We can test it once and close this issue if all looks good.

@maitreyie-chavan

**Comment by maitreyie-chavan** [comment]
@divyarajmasani This is still a valid issue, with addition of stories overlapping/appearing too close. Latest screenshot attached below 

![image](https://user-images.githubusercontent.com/20221326/103401533-2f2f1580-4b6f-11eb-9cd0-294fa573fce6.png)

**Comment by divyarajmasani** [comment]
On AMP pages we do not have control over number of slides shown, this may not be fixed but I've added the space between the stories. @maitreyie-chavan
