### ISSUE TITLE
'View all stories' related issues

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#4]
- [ ] **Grid view** 

Reproduction environment

- Enable `view all stories` option
- Allow anything more than 2 stories to appear
- Select the number of columns to be - 1
- Preview the post and towards the end the `view all stories` link appears left-aligned instead of centre. Reference image is below
<img width="330" alt="Screenshot 2020-11-01 at 8 39 53 PM" src="https://user-images.githubusercontent.com/20221326/97806664-dc2a0680-1c82-11eb-9736-97f4e0ce2782.png">

- [ ] **Carousel view**

- The `view all stories` option appears left-aligned in the backend and frontend. Reference image is below
<img width="871" alt="Screenshot 2020-11-01 at 8 35 05 PM" src="https://user-images.githubusercontent.com/20221326/97806538-029b7200-1c82-11eb-8928-53b3e30e1c9e.png">

**Comment by RahiDroid** [comment]
Hi @maitreyie-chavan 👋 
Do we want that archive link to be centered in all views?

**Comment by maitreyie-chavan** [comment]
@RahiDroid Aesthetically, the archive link would need to be centred only when stories are limited to a single column view space to go with the overall centred appearance of stories.

**Comment by divyarajmasani** [comment]
@maitreyie-chavan 
Keeping it centered for all views as it will be more easily visible to the users as they scroll.
