### ISSUE TITLE
Batch 0 Story 1  Cooking

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#404]
**Vertical** - Cooking

**Design** - https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=1613%3A840

**Asset Folder** - https://drive.google.com/drive/folders/11Yv6uFVUwH19km-NwLlyk4BVuWjMmfaN

**Comment by pooja-muchandikar** [comment]
### Test URL: https://google-webstories.rt.gw/ Batch 0 Story 1 Cooking

@kenrodriguesdesign 

I have checked the Cooking story and listed few points please do check.

- [ ] Screen 2 - the top space in actual screen is less not matching the figma
- [ ] Screen 2 - There shouldn't be horizontal line please refer the visual
<img width="1263" alt="Screenshot 2021-04-21 at 5 39 06 PM" src="https://user-images.githubusercontent.com/41000648/115551397-9e6c7900-a2c8-11eb-8a84-dc3d2098c8e9.png">

---

- [ ] Screen 3 - double quotation doesn't close
<img width="1256" alt="Screenshot 2021-04-21 at 5 48 18 PM" src="https://user-images.githubusercontent.com/41000648/115552307-cad4c500-a2c9-11eb-8a45-4cad23ca1cc8.png">

---

- [ ] Screen 4 - `6 Fast Rules For Making Bread` - there is more space between 3 and the jar icon not as per figma design
- [ ] Flour section - there is no space between the content and the arrow, also on click of the arrow/link gives error Refer Visual: https://drive.google.com/file/d/1Ov2i9AaRMEJQtMlnThkJFP0B5RGzJk_D/view
- [ ] `To knead or not to knead` screen - looks like the image is cropped [ Please check the images most looks cropped ] 
- [ ] `Beginner Bread Recipe` screen - The link should be https://www.google.com in preview also right? 
<img width="1274" alt="Screenshot 2021-04-21 at 5 46 50 PM" src="https://user-images.githubusercontent.com/41000648/115552137-8fd29180-a2c9-11eb-964e-bfc93bd12199.png">

---

cc: @maitreyie-chavan

**Comment by pooja-muchandikar** [comment]
@kenrodriguesdesign 

> Flour section - there is no space between the content and the arrow, also on click of the arrow/link gives error Refer Visual: https://drive.google.com/file/d/1Ov2i9AaRMEJQtMlnThkJFP0B5RGzJk_D/view

This link should work. 

@maitreyie-chavan everything is fine expect for the above issue.

**Comment by divyarajmasani** [comment]
PR For the template: https://github.com/google/web-stories-wp/pull/7944

**Comment by maitreyie-chavan** [comment]
Released in Web Stories 1.8.1v  https://github.com/google/web-stories-wp/releases/tag/v1.8.1
