### ISSUE TITLE
Share Button Issue

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#43]
If Title option is enabled - upon interacting with the Share button, the related `Get Link` option shows up behind the Title area. 

<img width="383" alt="Screenshot 2020-11-13 at 2 50 59 AM" src="https://user-images.githubusercontent.com/20221326/98998054-8a735d00-255b-11eb-827a-1a6bca0e5b4b.png">

**Comment by maitreyie-chavan** [comment]
To be discussed during the upcoming call.

**Comment by divyarajmasani** [comment]
We are removing the story player option from the block, this will no longer be an issue.
@maitreyie-chavan
