### ISSUE TITLE
Batch 1 Story 1 Entertainment

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#433]
Vertical - Entertainment

Design - https://www.figma.com/file/majSgyyvvfncHgLZHFKy8e/Stories---Template-Batch-1?node-id=6500%3A179

Asset Folder - https://drive.google.com/drive/folders/1JbzxnaBq45JQhviqIVtoQEj1vFF_XDJn

**Comment by divyarajmasani** [comment]
**Image Mapping for Batch 1 Story 1 - Entertainment**
-

|In WP |In Drive |
|--|--|
| batch1_entertainment_screen1 | batch1_entertainment_page1_bg
| batch1_entertainment_screen2 | batch1_entertainment_page2_bg
| batch1_entertainment_screen3 | batch1_entertainment_page3
| batch1_entertainment_screen4 | batch1_entertainment_page4_bg
| batch1_entertainment_screen5_image1 | batch1_entertainment_page5_image1
| batch1_entertainment_screen5_image2 | batch1_entertainment_page5_image2
| batch1_entertainment_screen6 | batch1_entertainment_page6_bg
| batch1_entertainment_screen7 | batch1_entertainment_page7
| batch1_entertainment_screen8 | batch1_entertainment_page8_bg
| batch1_entertainment_screen9 | batch1_entertainment_page9_bg
| batch1_entertainment_screen10 | batch1_entertainment_page10
| batch1_entertainment_screen11 | batch1_entertainment_page11_bg
| batch1_entertainment_screen12 | batch1_entertainment_page12_bg
| batch1_entertainment_screen13_image1 | batch1_entertainment_page13_image1
| batch1_entertainment_screen13_image2 | batch1_entertainment_page13_image2
| batch1_entertainment_screen14_image1 | batch1_entertainment_page14_image1
| batch1_entertainment_screen14_image2 | batch1_entertainment_page14_image2

**Comment by ganeshkerkar** [comment]
@divyarajmasani Below images has flattened and been uploaded as there was a linear issue.
- https://drive.google.com/file/d/1x6Uum4HB0r3QrQlpbqGRfUbtfShIdE_j/view?usp=sharing
- https://drive.google.com/file/d/1xYsJqfYqwOScqQd87zXsFxISJywvIlyl/view?usp=sharing
- https://drive.google.com/file/d/1m4M_APMuWN566IeFdTrAMsIwm1OZ4eLr/view?usp=sharing
