### ISSUE TITLE
Lightbox Effect - Close Button Issue

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#44]
If the cover image option is disabled and a user clicks on one of the stories, the close option does not appear when the lightbox effect is triggered.

**Comment by RahiDroid** [comment]
Hi @maitreyie-chavan , the reason of this is because we have added lightbox only when we are showing poster images. We can add lightbox for default embeds as well once we have #79 done as with current approach, adding lightbox for direct embeds increases the page load time by a lot.
