### ISSUE TITLE
Story Ad Tool: Add Preview button

### ISSUE THREAD

**Issue by swissspidy** [rtCamp/web-stories-wp#470]
## Task Description

It would be nice to bring back the Preview button in the editor for the story ad tool. `packages/output` should be able to generate the full HTML required for the story. Just need to make sure we can display media properly. (using blob URLs?)

**Comment by swissspidy** [comment]
cc @sayedtaqui 

Curious to hear how complex you think it would be

**Comment by sayedtaqui** [comment]
@swissspidy  That’s a great idea, I was thinking of doing the same.
The easiest way was to create a blob url and open it in a new tab for the markup by doing
```js
const blob = new Blob([markup], {type: "text/html"});
const url = URL.createObjectURL(blob);

window.open( url, 'preview' );
```
however, the only problem is that `amp4ads-v0.js`  will not load on a blob URL.

The other way I can think of is to keep a static placeholder preview.html  file with the following content, which will replace the entire DOM with the generated markup.
```html
<!doctype html>
<html>
<head>
<title>Generating Preview</title>
<script>
      function newContent() {
        const content = localStorage.getItem( 'previewMarkup' ) || 'Preview Expired';
        document.open();
        document.write( content );
        document.close();
      }
</script>
</head>
<body onload="newContent();" >
<p>Generating Preview</p>
</body>
</html>
```
And when they click on the preview button we store the markup and open it in a new url by doing
```js
localStorage.setItem( 'previewMarkup', markup );
window.open( window.location.origin + '/preview.html', 'preview' );
```
This url `app.com/preview.html`  will be active as long the user doesn’t reload the app.

**Comment by swissspidy** [comment]
`window.open('about:blank')` or `window.open( window.location.origin + '/preview.html', 'preview' );` with `document.write` doesn't work either I assume?

In that case, the `localStorage` (or perhaps `sessionStorage`?) approach seems like a viable workaround for now.

**Comment by sayedtaqui** [comment]
Yes, `sessionStorage` looks like a natural choice here however it doesn't work very well when working between tabs. For example, if I try to remove an item of sessionStorage on `app.com` it doesn't go away from `app.com/preview.html`.
See https://stackoverflow.com/questions/20325763/browser-sessionstorage-share-between-tabs

So it's easier to use `localStorage` and then get rid of it on `beforeunload` event in the app, so it's not available in the preview after the app is reloaded.

**Comment by sayedtaqui** [comment]
Closing as this was done as part of https://github.com/rtCamp/web-stories-ad-tool/pull/11
