### ISSUE TITLE
AMP-story-player To Play On Interaction

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#48]
Currently, once the page having embedded web stories is loaded with their cover images enabled - in the background, the stories are already auto-advancing even when not in the viewport. Due to which, when the user clicks on a story, it showcases story content from the middle leading them to miss out on pages from the story.

Ideally, when the user clicks on a story and the lightbox effect gets triggered, it should display the story content from the beginning/first page. 

This is a known issue of the player and is being tracked here - https://github.com/ampproject/amphtml/issues/29798

**Comment by divyarajmasani** [comment]
There has been an update on the mentioned issue, where it is stated that to stop story from being playing, it should not be in the viewport. So keeping stories/player hidden till user interacts with it resolves this issue upto an extent. Still adjacent stories does start loading in the background. 

Closing this for now. It will be best to create new issue based on further observations.
