### ISSUE TITLE
Show the "Ad" badge in the editor so users know how it would look like

### ISSUE THREAD

**Issue by amedina** [rtCamp/web-stories-wp#532]
AMP adds an "Ad" badge on the top left corner of ads. It would be useful to display that bardge in the editor for users to visualize it during creation time. 
<img width="514" alt="Screen Shot 2021-05-28 at 4 33 19 PM" src="https://user-images.githubusercontent.com/506089/120050620-6ac0f500-bfd2-11eb-9248-9d774232d5bc.png">

**Comment by sayedtaqui** [comment]
Closing as this was done as part of https://github.com/rtCamp/web-stories-ad-tool/pull/11
