### ISSUE TITLE
Batch 5 Story 7 Health and Wellness 1

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#642]
Vertical - Health and Wellness 

Design - https://www.figma.com/file/VCpGB5S9vyPPBnJsCivdGy/Stories---Template-Batch-5?node-id=7710%3A114

Asset Folder - https://drive.google.com/drive/folders/1UnESfomvtWkAV7Qs50EPzWQhjq9VjQxI

Story Link - https://google-webstories.rt.gw/web-stories/batch-5-story-7-health-and-wellness-1/

**Comment by ganeshkerkar** [comment]
@divyarajmasani The two stickers committed for this story were not used in the story so I have deleted it from the drive.

Stickers names 1. White Banner (whiteBanner.svg) and 2. Yellow Banner (yellowBanner.svg)
