### ISSUE TITLE
Grid view - Click event to trigger full view of stories

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#7]
**To-Do**

- [x] Make the title or entire story tile clickable which triggers a full-screen view of that story, similar to lightbox effect.
- [x] Provide an option to close/escape the full-screen view and return back to the site post/page.

**Comment by RahiDroid** [comment]
@maitreyie-chavan Can this be closed? Base functionality has been developed and one enhancement that's remaining has a separate issue #79

**Comment by maitreyie-chavan** [comment]
Yup, can be closed now.
