### ISSUE TITLE
Master issue to track all pull requests

### ISSUE THREAD

**Issue by rahul286** [rtCamp/web-stories-wp#72]
| Module                              | Branch                                | Related Issue(s) | PR Link |
|-------------------------------------|---------------------------------------|------------------|---------|
| PHP Class                           | rt/feature/php-api-stories            | 3064            |         |
| Gutenberg blocks (latest stories)   | rt/feature/gutenberg-latest-stories   | 3064            |         |
| Gutenberg blocks (selected stories) | rt/feature/gutenberg-selected-stories | 3064            |         |
| Customizer Options                  | rt/feature/customizer-options-stories | -                |         |
| Shortcode API                       | rt/feature/shortcode-api-stories      | -                |         |
| Sidebar Widget (classic)            | rt/feature/sidebar-widget-stories     | -                |         |
| TinyMCE Button                      | rt/feature/tnymce-stories             | -                |         |

**Comment by maitreyie-chavan** [comment]
Further to our discussion and as per the related separate issues being maintained, closing this issue now.
