### ISSUE TITLE
Inherit Typography

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/web-stories-wp#76]
The block should be able to inherit the typography based on the site's theme. Set a plan of implementation and any standards needed to handle font sizes for title and metadata. 

- [ ] remove font-family 
- [ ] foreground as well as background colors should be avoided as much as possible
- [ ] font-size declarations should be avoided as much as possible but if needed try using relative font-size first
- [ ] avoid alignment block (might fix #4)

**Test** 

- [ ] Test Data ➞ Create a page with all different type of Gutenberg block embedded in a page. e.g. a page stories embedded in list, grid, circle, carousel 
- [ ] Test Themes ➞ Default WP themes

**List of themes**

- [ ] https://wordpress.org/themes/twentytwenty/
- [ ] https://wordpress.org/themes/twentynineteen/
- [ ] https://wordpress.org/themes/twentyseventeen/
- [ ] https://wordpress.org/themes/twentysixteen/
- [ ] https://wordpress.org/themes/twentyfifteen/
- [ ] https://wordpress.org/themes/twentyfourteen/
- [ ] https://wordpress.org/themes/twentythirteen/

**Comment by divyarajmasani** [comment]
For the font sizes, I believe it will be best to set the sizes in `px` only. As the relative units are usually based on the font-size of the root element which can vary on different themes. So even if we set values assuming `16px` base it may cause issues on themes where the base font-size is different.

- Have removed the font-family declaration.
- Removing a few background-color declarations.
- Aligning the `View All Stories` link to the center.

I haven't pushed these changes just yet, I'm moving to @RahiDroid's PRs for now.

@rahul286 @maitreyie-chavan

**Comment by maitreyie-chavan** [comment]
@divyarajmasani I believe we have already taken care of this, I'll go ahead and close the issue. However, will make a note of it while testing across various themes. 

cc @pooja-muchandikar
