### ISSUE TITLE
Lightbox: Have single lightbox for all stories instead of having separate ones for all

### ISSUE THREAD

**Issue by RahiDroid** [rtCamp/web-stories-wp#79]
## Feature Description
- Currently we are loading in separate stories in separate lightbox even if user isn't looking at the lightbox, which affects the performance and increases the page load time.
- We need to have single lightbox and show stories only when user clicks on a specific story. For that the markup could be similar to this,
```
<amp-story-player>
    <a href="story-link-1">
    <a href="story-link-2">
    <a href="story-link-3">
</amp-story-player>
```
Now when user clicks on respective story, we need to show that story using `.show()` method on the story player.
- We can possibly use [amp-script](https://amp.dev/documentation/components/amp-script/) component for running the JS for this.

## Alternatives Considered
- Just chaning the url in story player or changing story player's markup entirely doesn't work as `amp-story-player` js seems to load stories only on page load. (Will do further investigation on this)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by RahiDroid** [comment]
#42 will most likely be fixed by this.

CC: @divyarajmasani @maitreyie-chavan

**Comment by RahiDroid** [comment]
@divyarajmasani Did you get a chance to look at the error I was talking about while using `<amp-script>`?

**Comment by RahiDroid** [comment]
Update: Scope of this issue has been extended. Because of conflicts with AMP Runtime JS, we will be using separate custom script on non-AMP pages and for AMP pages, we will use `<amp-script>` component (which seems to be working at the moment, but it's working with inline script and not separate script). I am working on it currently, will try and finish it today.

**Comment by divyarajmasani** [comment]
We can close this issue now, as mentioned in #115 , we have implemented above mentioned for non-AMP pages.

@maitreyie-chavan
